apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: image-reflector
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: image-reflector-controller
      version: "0.23.0" # Replace with the latest version
      sourceRef:
        kind: HelmRepository
        name: flux-system
        namespace: flux-system
      interval: 1m