apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: update-server-entrypage
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: master
    commit:
      author:
        name: Flux-bot
        email: flux@thefoxnet.co.uk
      messageTemplate: 'Update image for server-entrypage to {{.ImageTag}}'
    push:
      branch: master
  update:
    path: ./apps/base/server-entrypage