# This is all you need for dynamic provisioning via CSI.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-config
  namespace: arctic
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  volumeName: app-config