apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  namespace: arctic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      containers:
      - name: home-assistant
        image: ghcr.io/home-assistant/home-assistant:stable
        env:
        - name: HASS_CONFIG
          value: /mnt/app-config/hass-config
        ports:
        - containerPort: 8123
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        volumeMounts:
        - name: app-config
          mountPath: /mnt/app-config
      volumes:
      - name: app-config
        persistentVolumeClaim:
          claimName: app-config