apiVersion: apps/v1
kind: Deployment
metadata:
  name: samba-server
  namespace: arctic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samba-server
  template:
    metadata:
      labels:
        app: samba-server
    spec:
      containers:
      - name: samba
        image: dperson/samba:latest
        args:
          - "-n"  # Start nmbd daemon
          - "-g"
          - "netbios name = arctic"  # Set NetBIOS name
          - "-w"
          - "WORKGROUP"  # Set the workgroup
          - "-g"
          - "server string = Arctic Samba Server"  # Optional description
          - "-s"
          - "app-config;/shares/app-config;yes;no;yes;;;;;;;;"  # Share config
        ports:
          - name: smb
            containerPort: 445
            protocol: TCP
          - name: netbios
            containerPort: 139
            protocol: TCP
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        volumeMounts:
          - name: app-config
            mountPath: /shares/app-config
      volumes:
        - name: app-config
          persistentVolumeClaim:
            claimName: app-config
---
apiVersion: v1
kind: Service
metadata:
  name: samba-server
  namespace: arctic
spec:
  type: LoadBalancer
  selector:
    app: samba-server
  ports:
    - name: smb
      protocol: TCP
      port: 445
      targetPort: 445
    - name: netbios
      protocol: TCP
      port: 139
      targetPort: 139