apiVersion: apps/v1
kind: Deployment
metadata:
  name: samba-server
  namespace: arctic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samba-server
  template:
    metadata:
      labels:
        app: samba-server
    spec:
      containers:
      - name: samba
        image: dperson/samba:latest
        args:
          # netbios name (-n), set to "arctic"
          - "-n"
          - "arctic"
          # workgroup (-w), default is WORKGROUP, but let's be explicit
          - "-w"
          - "WORKGROUP"
          # enable guest (-g), so Samba actually allows the guest account
          - "-g"
          # enable avahi/mdns (-m), helpful for Mac discovery
          - "-m"
          # define the share (-s):
          # "shareName;/shares/app-config;browsable;readonly;guest_ok;users;admins;acl;comment;inherit;hostsallow;hostsdeny"
          - "-s"
          - "app-config;/shares/app-config;yes;no;yes;;;;;;;;"
        ports:
          - name: smb
            containerPort: 445
            protocol: TCP
          - name: netbios
            containerPort: 139
            protocol: TCP
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        volumeMounts:
          - name: app-config
            mountPath: /shares/app-config
      volumes:
        - name: app-config
          persistentVolumeClaim:
            claimName: app-config
---
apiVersion: v1
kind: Service
metadata:
  name: samba-server
  namespace: arctic
spec:
  type: LoadBalancer
  selector:
    app: samba-server
  ports:
    - name: smb
      protocol: TCP
      port: 445
      targetPort: 445
    - name: netbios
      protocol: TCP
      port: 139
      targetPort: 139