apiVersion: apps/v1
kind: Deployment
metadata:
  name: samba-server
  namespace: arctic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samba-server
  template:
    metadata:
      labels:
        app: samba-server
    spec:
      initContainers:
      - name: create-samba-user
        image: dperson/samba
        command:
          - /bin/sh
          - -c
          - |
            ADMIN_USER=$(cat /run/secrets/admin-user)
            ADMIN_PASS=$(cat /run/secrets/admin-pass)
            smbpasswd -a -n $ADMIN_USER
            echo -e "$ADMIN_PASS\n$ADMIN_PASS" | smbpasswd -s -a $ADMIN_USER
        volumeMounts:
        - name: samba-secrets
          mountPath: /run/secrets
          readOnly: true
      containers:
      - name: samba-server
        image: dperson/samba
        command: ["/usr/bin/smbd", "-FS", "-s", "/etc/samba/smb.conf"]
        ports:
        - containerPort: 445
        volumeMounts:
        - name: app-config
          mountPath: /mnt/share
        - name: samba-config
          mountPath: /etc/samba/smb.conf
          subPath: smb.conf
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
      volumes:
      - name: app-config
        persistentVolumeClaim:
          claimName: app-config
      - name: samba-config
        configMap:
          name: samba-config
      - name: samba-secrets
        secret:
          secretName: secrets
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: samba-config
  namespace: arctic
data:
  smb.conf: |
    [global]
    workgroup = WORKGROUP
    security = user
    map to guest = Bad User

    [app-config]
    path = /mnt/share
    browseable = yes
    writable = yes
    guest ok = yes
    valid users = @smbusers
---
apiVersion: v1
kind: Service
metadata:
  name: samba-server
  namespace: arctic
spec:
  type: LoadBalancer
  selector:
    app: samba-server
  ports:
    - protocol: TCP
      port: 445
      targetPort: 445