apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/controllers/base/cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m