apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-foxnet-certificate
  namespace: cert-manager
spec:
  secretName: wildcard-foxnet-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - "*.foxnet"
    - foxnet