apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - configmap.yaml
  - ingress.yaml
  - certificate.yaml
  - issuer.yaml
  - cert-manager-kustomization.yaml