---
- name: Install Samba
  ansible.builtin.package:
    name: samba
    state: present
    update_cache: yes
  become: true
  
- name: Ensure ~/shares directory exists
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/shares"
    state: directory
    mode: "0755"
    owner: "nobody"
    group: "nogroup"
  become: true

- name: Ensure filestore share exists
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/shares/filestore"
    state: directory
    mode: "0755"
    owner: "nobody"
    group: "nogroup"
  become: true

- name: Fix ownership of existing files in shares
  ansible.builtin.command:
    cmd: chown -R nobody:nogroup /home/{{ ansible_user }}/shares/
  become: true

- name: Configure Samba
  ansible.builtin.template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
  become: true

- name: Restart Samba service
  block:
    - name: Restart smbd service
      ansible.builtin.service:
        name: smbd
        state: restarted
      become: true
      when: not ansible_check_mode

    - name: Mock Samba service restart in check mode
      ansible.builtin.debug:
        msg: "Dry run: Would have restarted the Samba service (smbd)."
      when: ansible_check_mode