---
- name: Add HashiCorp GPG key using apt_key
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present
  become: true

- name: Add HashiCorp APT Repository
  ansible.builtin.apt_repository:
    repo: "deb https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present
  become: true

- name: Install Terraform
  ansible.builtin.apt:
    name: terraform
    state: present
    update_cache: yes
  become: true

# Authenticate with Terraform Cloud API
- name: Ensure Terraform Cloud API Token is set in .zshrc
  ansible.builtin.lineinfile:
    path: /home/{{ ansible_user }}/.zshrc
    line: 'export TF_TOKEN_app_terraform_io={{ terraform_api_token }}'
    create: yes
  become: true

- name: Load Terraform API Token into shell environment
  ansible.builtin.shell: zsh -c "source /home/{{ ansible_user }}/.zshrc"
  become: true