apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  targetNamespace: ingress-nginx
  interval: 10m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.12.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  install:
    createNamespace: true
  values:
    fullnameOverride: ingress-nginx
    controller:
      service:
        type: LoadBalancer
      ingressClassResource:
        default: true
    admissionWebhooks:
      enabled: true
    patch:
      enabled: true