apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./controllers/base/cert-manager
  - ./controllers/base/sealed-secrets
  - ./controllers/base/ingress-nginx
  - ./controllers/base/longhorn
  - ./controllers/base/rancher
  - ./controllers/base/metallb
  - ./controllers/base/image-automation-controller
  - ./controllers/base/image-reflector-controller
  - ./configs/crds
  - ./configs/image-automation