apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./controllers/base/sealed-secrets
  - ./controllers/base/rancher
  - ./controllers/base/metallb
  - ./controllers/base/longhorn
  - ./controllers/base/samba-server
  - ./configs/crds
  - ./configs/image-automation
  - ./configs/sealed-secrets.yaml
  - ./volumes