apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/controllers/base/sealed-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: sealed-secrets