apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  targetNamespace: sealed-secrets
  interval: 10m
  chart:
    spec:
      chart: sealed-secrets
      version: 0.17.4
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets-repo
        namespace: flux-system
  values:
    installCRDs: true  # Ensures the required CRDs are installed