name: Terraform on Arctic

on:
  push:
    paths:
      - 'servers/arctic/terraform/**'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Ansible to Execute Terraform on Arctic
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: 10.56.1.30
          username: foxleigh81
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            ansible-playbook -i /home/foxleigh81/ansible/inventories/foxnet.ini /home/foxleigh81/ansible/playbooks/terraform.yml